### ISSUE TITLE
About update host inventory

### ISSUE THREAD

**Issue by xuebb** [lukecyca/pyzabbix#104]
https://www.zabbix.com/documentation/3.4/manual/api/reference/host/update#updating_host_inventory

zapi.host.update(hostid='10357',inventory='{"location":"LA"}')
this does not work . the record in host_inventory table does not update.
does the pyzabbix support the updating host inventory?

**Comment by naktu** [comment]
Can you send this request to API by example curl?

**Comment by lukecyca** [comment]
I don't think you want to quote the `inventory` parameter as a string. Just make it a Python dict. All the parameters will be JSONified prior to sending it to the Zabbix Server's API endpoint.

**Comment by xuebb** [comment]
Thank U. It works. 
zapi.host.update(hostid='10357',inventory={"location":"LA"})
