### ISSUE TITLE
<Unknown Trigger> [<Unknown Triggerid>] <Unknown Severity>

### ISSUE THREAD

**Issue by JVS111** [lukecyca/pyzabbix#108]
Use zabbix-gnomes to collect events, specifically zeventfinder.py.
The problem that I find is that, sometimes it happens, the trigger name, the trigger id and the severity are not received and we find lines like this:

2018-08-22 01:13:09 (UTC) CRM System: OK [548398] Unknown Trigger [Unknown Triggerid] (Unknown Severity | Ack: No)

If we analyze the response captured with Wireshark we will see that the API YES that returns all the values that have been omitted.

It could be a problem with the zapy.event.get (** call) method,

Could I access the get method code to see what's wrong?

Thank you
a greeting

**Comment by neothematrix** [comment]
Hi,
I guess you can change zeventfinder.py code to enable debug logging as described here: https://github.com/lukecyca/pyzabbix#enabling-debug-logging

when the issue arises you will be able to see exactly what was sent to the Zabbix API and what's been received back by pyzabbix.

Keep in mind, pyzabbix does not implement the "event.get" method, we just forward the query to the Zabbix API as it is received.

**Comment by neothematrix** [comment]
I'm closing this, if you still have issue, please reopen.
thanks!
