### ISSUE TITLE
(u'Error -32602: Invalid params., Wrong fields for trigger.', -32602)

### ISSUE THREAD

**Issue by AweiWoo** [lukecyca/pyzabbix#109]
Hi:

I use trigger.create to add trigger, but it's faild, as follow:

**(u'Error -32602: Invalid params., Wrong fields for trigger.', -32602)**

My code like this:

def create_trigger_for_webscenario(auth,host_name,scenario_name,URL):
	expression='{'+'{0}:web.test.rspcode[{1},index].count(180,399,"gt")'.format(host_name,scenario_name) + '} >3 or {'+'{0}:web.test.fail[{1}].count(180,0,"ne")'.format(host_name,scenario_name)+'}=3'
	try:	
		auth.trigger.create(params={'description' : '[WEB]-{HOST.NAME} ：'+'{0} 
 xxxxxxxx({1})'.format(scenario_name,URL),"expression": expression,"priority":3})
	except Exception as e:
		print e

How can i use trigger.create , can you give a expamle for me ?  thanks.

**Comment by AweiWoo** [comment]
when I use ZabbixAPI.do_request  is OK !
  ZabbixAPI.do_request(auth, 'trigger.create', params={'description' : '[WEB]-{HOST.NAME} ：'+'{0}XXXXXXX({1})'.format(scenario_name,URL),"expression": expression,"priority":3})

**Comment by neothematrix** [comment]
hi,
try passing the "expression" variable as reference (note the *expression notation):

`auth.trigger.create(params={'description' : '[WEB]-{HOST.NAME} ：'+'{0}
xxxxxxxx({1})'.format(scenario_name,URL),"expression": *expression,"priority":3})`
