### ISSUE TITLE
some plan for zabbix4.0?

### ISSUE THREAD

**Issue by veryrich** [lukecyca/pyzabbix#111]

**Comment by neothematrix** [comment]
ciao,
I haven't tried pyzabbix with 4.0, I'm still on 3.4, did you try it and find issues?

**Comment by boyemillar** [comment]
event.acknowledge is not working on 4.0

`Traceback (most recent call last):
  File "./test2.py", line 26, in <module>
    zapi.event.acknowledge({"eventids": "28100401","action": 6,"message": "Problem resolved."})
  File "/usr/lib/python2.7/site-packages/pyzabbix/__init__.py", line 157, in fn
    args or kwargs
  File "/usr/lib/python2.7/site-packages/pyzabbix/__init__.py", line 134, in do_request
    raise ZabbixAPIException(msg, response_json['error']['code'])
pyzabbix.ZabbixAPIException: (u'Error -32602: Invalid params., Incorrect arguments passed to function.', -32602)
`

**Comment by neothematrix** [comment]
@boyemillar works for me, just tested with Zabbix 4.0.1:
>> zapi.event.acknowledge(eventids=50435,action=6,message='test')
{u'eventids': [50435]}

are you sure you're passing all the parameters properly?

**Comment by boyemillar** [comment]
Sorry Gabriele you are correct it was my understanding of how to use the API... It is working fine using your method above.

**Comment by neothematrix** [comment]
good, I'm closing this, thanks for your feedback
