### ISSUE TITLE
Where does "self.user" come from?

### ISSUE THREAD

**Issue by dbergmanskytap** [lukecyca/pyzabbix#114]
Hi,
This is more a question than an issue, but I wasn't sure the best way to post it otherwise. My team is using your pyzabbix tool and I have 2 questions I wanted to ask you about the ZabbixAPI class, and specifically about the login() method. 
1) login() references "self.user.login()" and "self.user.authenticate()" however, I don't see where a value is set for self.user itself. Since the ZabbixAPI class inherits directly from Object, it doesn't seem to come from a parent class. Where are these methods defined and where does the user value come from?
2) in the case that login() failed due to faulty credentials, is there a specific Exception type that would be raised? where would this exception be found?
Thanks!

**Comment by neothematrix** [comment]
Hello!
user.login and user.authenticate (deprecated on new zabbix versions) are directly sent to the Zabbix API as methods (https://www.zabbix.com/documentation/3.0/manual/api/reference/user/login). Pyzabbix is a very light library that translates any request into an json API call (do_request()) to the Zabbix API without mapping or checking them.

Any exception is also "generic" and raised as "ZabbixAPIException", you might find the reason of the exception in the error message that is sent back directly from the zabbix API.

**Comment by dbergmanskytap** [comment]
thanks!
