### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by lordievader** [lukecyca/pyzabbix#120]
Please distribute the license with the code. In the readme there is a link to the license this code falls under. I think it would be better to explicitly distribute the license with the code.
Githuvlb makes it easy to include the chosen license.

**Comment by lukecyca** [comment]
The license is on the bottom of the front page (in the README). It is also in the `setup.py` metadata so it shows up on [PyPI](https://pypi.org/project/pyzabbix/).
