### ISSUE TITLE
groupid

### ISSUE THREAD

**Issue by ognjen011** [lukecyca/pyzabbix#121]
How do i get groupid using pyzabbix? I tried many variations of this but i always get a list of all groups i only want a groupid of the group i created or if there is group there already with that name. I am parsing a csv file and creating hosts and groups on import but i can only create a host once i have correct groupid.

groups_id = zapi.hostgroup.get({"extend":"groupid","filter": {"name":group.split(",")}}) 

Can someone point me in the right direction.

**Comment by lordievader** [comment]
I have a function for just this, it's in my [zbxtoolkit/functions.py][1], lines 76 through 107.

[1]: https://github.com/lordievader/zbxtoolkit/blob/master/zbxtoolkit/functions.py

**Comment by paalbra** [comment]
`hostgroup.get` and `hostgroup.create` both returns ids.

If you know the name(s) of the group(s) just do something like:
```python
# Multiple
hostgroup_ids = [hostgroup["groupid"] for hostgroup in api.hostgroup.get(filter={"name": ["A", "B"]})]
# Single
hostgroup_id = api.hostgroup.get(filter={"name": "B"})[0]["groupid"]
```
If this is a group you created the id is returned:
```python
hostgroup_id = api.hostgroup.create(name="X")["groupids"][0]
```

You probably want to error handle this though. The groups might exist/not exist.
