### ISSUE TITLE
Zabbix Sender Implementation?

### ISSUE THREAD

**Issue by LopezNathan** [lukecyca/pyzabbix#128]
Quick question, do you have any plans to implement the Zabbix Sender into this module?

Thank you for the awesome module!

**Comment by neothematrix** [comment]
ciao @LopezNathan, it would be an awesome addition indeed, I looked into implementing it a few years ago, but unfortunately, it's a huge amount of work and I don't currently have the time to do that at the moment.
If you are up for it, consider submitting a PR!
thanks!

**Comment by LopezNathan** [comment]
Definitely understand! Thank you for the response.
I will certainly check over what work is needed for this.
