### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by cgtobi** [lukecyca/pyzabbix#130]
Hi all,

I try to get this running but I must be doing something wrong. I get `Not authorised.` when running the following script:

```python
from pyzabbix import ZabbixAPI

API_SERVER = "https://zabbix.foo.bar/zabbix"
API_USER = "api_user"
API_PASSWORD = "secret_password"

with ZabbixAPI(API_SERVER) as zapi:
    zapi.session.verify = False
    zapi.session.auth = (API_USER, API_PASSWORD)
    zapi.login = (API_USER, API_PASSWORD)
    hg = zapi.do_request("hostgroup.get")
```

Debug logging gives the following:

```
JSON-RPC Server Endpoint: https://zabbix.foo.bar/zabbix/api_jsonrpc.php
Sending: {
    "jsonrpc": "2.0",
    "method": "hostgroup.get",
    "params": {},
    "id": 0
}

Response Code: 200
Response Body: {
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params.",
        "data": "Not authorised."
    },
    "id": 0
}
```

Can someone point me in the right direction?

Thanks in advance,
cgtobi

**Comment by neothematrix** [comment]
ciao, why are you using both zapi.session.auth and zapi.login? do you use http authentication on zabbix? if so, and if you upgraded zabbix recently, please consider the changes on http auth that were introduced with zabbix 4.0: https://www.zabbix.com/documentation/4.0/manual/installation/upgrade_notes_400#http_authentication

**Comment by cgtobi** [comment]
Hi Gabriel, thanks for the quick response. Forgive my ignorance I just started using this and zabbix and I am just trying to consume data, I am not actually working with zabbix. I just added `zapi.session.auth` as it didn't work without it either and it was not clear to me from the documentation how to actually use it. No we don't use http auth (AFAIK).

**Comment by neothematrix** [comment]
ok, then you don't need to use zapi.session.auth that's only if you have HTTP authentication configured in Zabbix, just use zapi.login('user','password') if you still get the error, doublecheck your credentials

**Comment by cgtobi** [comment]
Well, the curious thing is that a php script with the same credentials works fine from the same machine. That's what I don't get.

**Comment by neothematrix** [comment]
which zabbix version are you connecting to? you can check that with zapi.api_version() if you don't have access to the frontend

**Comment by cgtobi** [comment]
No, that works fine:
```
Response Body: {
    "jsonrpc": "2.0",
    "result": "4.2.6",
    "id": 0
}
```

The installed version is 4.2.6.

**Comment by neothematrix** [comment]
can you paste the debug for the zapi.login call? of course you can edit out user/password
thanks

**Comment by neothematrix** [comment]
ok found the issue, zapi.login() is a function you need to pass username and password as parameter:

change:
` zapi.login = (API_USER, API_PASSWORD)`
with:
`zapi.login(API_USER,API_PASSWORD)`

and everything will start working :)

**Comment by cgtobi** [comment]
Good god that is embarrassing. As if I had never written any python code. 🙃

Thanks. That was a really stupid mistake y
