### ISSUE TITLE
zapi.usermacro.get({ "output": "extend", "globalmacro": 'true' }) does not return global macros

### ISSUE THREAD

**Issue by stevereaver** [lukecyca/pyzabbix#132]
Posting;  zapi.usermacro.get({ "output": "extend", "globalmacro": 'true' })   does not return global macros, however it returns all host and template macros. 

I have tested this against my server with curl;

curl -i -X POST -H 'Content-Type: application/json-rpc' -d '{ "jsonrpc": "2.0", "method": "usermacro.get", "params": { "output": "extend", "globalmacro": true }, "auth": "9375f9f35adae0ed9f6983260a0cbb15", "id": 1 }' http://zabbix/zabbix/api_jsonrpc.php

and get the expected result, ie: the global macros are returned.

**Comment by neothematrix** [comment]
hello @stevereaver,
thanks for your message!
I'm not sure if you've gotten that example of code somewhere, but that's not the right way to call pyzabbix methods, please check the examples and you'll see.
The correct way to call api method with parameters is, in your example:

`zapi.usermacro.get(output="extend", globalmacro="true")`

p.s. you could write anything as value for "globalmacro", as long as the parameter is there, it's just a "flag" for zabbix, so: globalmacro=True, globalmacro="hello", all these would work.
