### ISSUE TITLE
host.get is not returning tags

### ISSUE THREAD

**Issue by ikzelf** [lukecyca/pyzabbix#133]
def host_lookup(groupid):
    groupids = groupid

    return zapi.host.get(groupids=groupids,
                           output="extend",
                           selectInventory=['alias'],
                           selectTags=[{'tag': 'APP'}],
                           tags=[{'tag': 'OTAP', 'value': 'prd', 'operator': 0}
                                ]
                           )

The filtering is working OK, I get all hosts within the groups that have OTAP 'prd'.
The selectTags is not working I do get tags returned with 
[{'tag': None, 'value': None}, {'tag': None, 'value': None}]
not with the tag names and not with the tag values.
For hosts that have multiple tags, I do get an entry for all of them.

What I was hoping for: the selected tags with their values (or all tags with their values)
Using:
zabbix 4.4.3
python 3.6.5
pyzabbix 0.7.5

I might be using this wrong, in that case, please educate me.
Thanks,
Ronald.

**Comment by neothematrix** [comment]
ciao @ikzelf ,
your query is not correct, try using `selectTags="extend"` instead of `selectTags=[{'tag': 'APP'}]`

**Comment by ikzelf** [comment]
Thanks for the help,
it works now.
🥇
