### ISSUE TITLE
Adding hosts, failing

### ISSUE THREAD

**Issue by samip5** [lukecyca/pyzabbix#140]
Why am I getting this error?

Code snippet:
```py
                device_label = value['Device Label']
                device_label = re.sub(pattern, "", device_label)
                params = {
                    "host": f"{device_label}",
                    "interfaces": {
                        "type": 2,
                        "main": 1,
                        "useip": 1,
                        "ip": f"{value['IP Address']}",
                        "dns": "",
                        "port": "161",
                        "details": {
                            "version": 2,
                            "bulk": 1,
                            "community": "{$SNMP_COMMUNITY}",
                        },
                    },
                    "groups": {
                        "groupid": "32"
                    },
                    "templates": {
                        "templateid": "10250"
                    },
                    "macros": {
                        "macro": "{$SNMP_COMMUNITY}",
                        "value": "<community-string>"
                    }
                }
```

Error: 
```
Response Code: 200
Response Body: {
    "jsonrpc": "2.0",
    "error": {
        "code": -32500,
        "message": "Application error.",
        "data": "No permissions to referred object or it does not exist!"
    },
    "id": 448
}
```

**Comment by neothematrix** [comment]
ciao,
the params syntax is not correct:
"macros", "groups" and "interfaces" should all be arrays of dict, not just dict, so change them into something like:
`"groups": [{
  "groupid": "32"
}],
`
also not sure if it's a cut and paste issue but hostname doesn't look correct:
`"host": f"{device_label}",`
should probably be:
`"host": device_label,`

try fixing these issues and it should work.
I noticed you're using "details" in the host interface, are you using zabbix v5.x?

**Comment by samip5** [comment]
> ciao,
> the params syntax is not correct:
> "macros", "groups" and "interfaces" should all be arrays of dict, not just dict, so change them into something like:
> `"groups": [{ "groupid": "32" }], `
> also not sure if it's a cut and paste issue but hostname doesn't look correct:
> `"host": f"{device_label}",`
> should probably be:
> `"host": device_label,`
> 
> try fixing these issues and it should work.
> I noticed you're using "details" in the host interface, are you using zabbix v5.x?

Yes, using Zabbix 5.0 and that device label is using a f-string, which does get populated correctly.

**Comment by neothematrix** [comment]
great, did you try changing the groups,interfaces and macros to be arrays?

**Comment by samip5** [comment]
Yes, that worked but how do I set the proxy to use aswell?

**Comment by neothematrix** [comment]
good.
for the proxy, just add another parameter:
`"proxy_hostid":"<id of the zabbix proxy"`

**Comment by samip5** [comment]
Ah, thank you, that worked perfectly. (Managed to crash the Zabbix server too, due to out of memory, aka cache was too small.)

My automatic discovery rules did not work so that's why I'm adding them though the API. 
https://www.zabbix.com/forum/zabbix-help/404449-figuring-out-the-automatic-discovery-of-network-devices

**Comment by neothematrix** [comment]
added a comment on your forum post too that should fix your issue with the discovery ;-)
feel free to close this Git issue as I guess all is working properly.
thanks!
