### ISSUE TITLE
[Help request]: Going though all devices and disabling all interface triggers except some

### ISSUE THREAD

**Issue by samip5** [lukecyca/pyzabbix#141]
I know that this is most likely not the right place to ask for help, but I'm giving it a shot.

I'm trying to programmically go though all of my network devices (200+), and only have uplinks triggers enabled, and disable all of the other interfaces triggers. I would much appreciate some pointers on how to go about it? I'm definitely not wanting to do them by hand.

This is basically it, what I have tried to just get all of the devices first.

```py
params = {
       "groupids": "32"
    }

    zabi.do_request("host.get", params)
```

**Comment by neothematrix** [comment]
@samip5, thanks for your message but the right place to ask would be the [Zabbix community forum](https://www.zabbix.com/forum/zabbix-help), you'll find many more people reading that and able to help.

**Comment by samip5** [comment]
Usually on the forum that's not the case.  :(

**Comment by samip5** [comment]
You can see what I mean: https://www.zabbix.com/forum/zabbix-help/405977-mass-updating-devices-triggers-via-api-and-python-3. No reply whatsoever. :(
