### ISSUE TITLE
Add parameter to disable SSL

### ISSUE THREAD

**Issue by juliosaraiva** [lukecyca/pyzabbix#142]
```
zabbix = ZabbixAPI('https://monitoring.zabbix.com')
zabbix.login(user='Admin', password='zabbix')
```
When I'm trying to use the API I'm receiving this error.
```
SSLError: HTTPSConnectionPool(host='monitoring.zabbix.com', port=443): Max retries exceeded with url: /api_jsonrpc.php 
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: 
unable to get local issuer certificate (_ssl.c:1108)')))
```

**Comment by juliosaraiva** [comment]
working using zapi.session

**Comment by jason-brian-anderson** [comment]
could you elaborate any on this?  

zabbix = ZabbixAPI('https://monitoring.zabbix.com')

never successfully executes in the first place so there is no way to set any attributes like session on it.

**Comment by jason-brian-anderson** [comment]
This worked fine for me:

import pyzabbix
import requests


session = requests.Session()
session.verify = False

zapi = pyzabbix.ZabbixAPI(ZABBIX_SERVER, 
                          session = session,
                         )

# Login to the Zabbix API
zapi.login(user, pwd)
