### ISSUE TITLE
Get method returns None to JSON

### ISSUE THREAD

**Issue by wmorgue** [lukecyca/pyzabbix#145]
Hi 👋🏻

When I print a raw data from a function below, I got both a `JSON` data and `None`.

```python
    def get_sla(self, by_service_ids: list = [2]) -> dict:
        data = self.zabbix.service.getsla(
            serviceids=by_service_ids, intervals={"from": 1397555080, "to": 1393655080}
        )

        print(data)
```

I get the data below:

```text
{'2': {'status': '0', 'problems': [], 'sla': [{'from': 1397555080, 'to': 1393655080, 'sla': 100, 'okTime': 0, 'problemTime': 0, 'downtimeTime': 0}]}}
None

```

I have no idea why I get `None` from this `service.getsla` method. Other methods such as `host.get` or `service.get` also return a `None`.
This makes parsing difficult and leads to an array error.

Help me understand why I get a `None` instead of a pure `JSON`.

**Comment by neothematrix** [comment]
ciao @wmorgue ,
thanks for your report.
I tested a direct call to zabbix.server.getsla() and the result is just a json, I guess it has something to do with your definition of the "get_sla" function or the way you call it.
How do you call the function? what parameters are you passing?
thanks

**Comment by wmorgue** [comment]
Thanks for response @neothematrix 

Hmm, I retested this method in a separate file and did not get `None`.
The error was in the duplicate `print()` call 😅
