### ISSUE TITLE
Very slow login with pyzabbix 0.8.2, Zabbix 5.0 and Python 3.8.2

### ISSUE THREAD

**Issue by Javihache** [lukecyca/pyzabbix#149]
I can reproduce this on my server using simply 

```
zapi.login("username", "password")
print("Connected to Zabbix")
```

On CLI I call the script with `python3 -v TestZabbixConnection.py`
The script stops for around 1min at:

```
import 'shlex' # <_frozen_importlib_external.SourceFileLoader object at 0x10a50c0a0>
import 'netrc' # <_frozen_importlib_external.SourceFileLoader object at 0x10a500af0>

```
then it finally resumes and finishes. 

What could be the problem? Some option on Zabbix-server.conf maybe? When I open the GUI the server is super responsive and fast.

Also I have just realized that if I use http://zabbixIP/zabbix instead of https://zabbixFQDN the response is lightning fast. If I use https://zabbixIP/zabbix I get a certificate error. Any ideas?

**Comment by neothematrix** [comment]
hi!
I don't think this is an issue with pyZabbix, check your DNS servers maybe you have an unresponsive or wrong one that slows down the resolution of "zabbixFQDN".
Also, try opening "http://zabbixFQDN" to see if the slowness of login appears only while using https.
Finally, try opening a python3 shell and just try importing "shlex" and "netrc", if it gets stuck for a long time just at importing those libraries, the issue could be somewhere else.

**Comment by Javihache** [comment]
Thanks for the fast response neo! 

My DNS is both in computer and router 1.1.1.1
Opening https://zabbixFQDN or http://zabbixFQDN on a browser, opens the GUI very fast.

Opening a python console and typing import netrc or import shlex work fast too. I didn't see any delay there. And anyway the same modules get imported when I use http://zabbixIP/zabbix and it goes super fast.

Using http://zabbixFQDN is same slow. My Apache redirects to HTTPS anyway so I guess that's the reason.

Somehow I am guessing a problem with the way pyzabbix deals with HTTPS connections maybe?



I

**Comment by neothematrix** [comment]
pyzabbix uses the "requests" library to handle https, if it's an issue with https you should see the same behavior trying to open https://zabbixFQDN directly using requests.get('https://zabbixFQDN') for example.
can you try using zapi.api_version before the login to see if the response is delayed also with that call that shouldn't use login?

**Comment by Javihache** [comment]
Same problem with requests doing requests.get('https://zabbixFQDN') and with zapi.api_version. 


I tried turning off the redirect engine on the 000-default.conf at apache, but when I load http://zabbixFQDN from the browser it redirects to the HTTPS site anyway... might that have anything to do with this problem although the HTTPS site loads perfectly fast on browsers?

**Comment by neothematrix** [comment]
Well if also requests.get is slow, then I guess this confirms it's not an issue with pyzabbix. I'd try to search if there are reports of similar issue with requests library directly, for example a quick search lead to this issue: https://github.com/psf/requests/issues/4023, but it's just an example.
Let us know if you find something!
