### ISSUE TITLE
Unsecure SSL certificate when declaring object

### ISSUE THREAD

**Issue by TheNetworkGuy** [lukecyca/pyzabbix#157]
I might be wrong here, but could the combination of #150 and an invalid SSL certificate call for an requests.exceptions.SSLError when declaring the object?

Setup:
 - Using Pyzabbix version 1.0
 - Python 3.6.8

import pyzabbix
pyzabbix.ZabbixAPI("https://zabbix-with-self-signed-cert.local")

Will result in the following:
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https://zabbix-with-self-signed-cert.local', port=443): Max retries exceeded with url: /api_jsonrpc.php (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
requests.exceptions.SSLError: HTTPSConnectionPool(host='https://zabbix-with-self-signed-cert.local', port=443): Max retries exceeded with url: /api_jsonrpc.php (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

Just to clarify: this happens when declaring the object. I don't have a chance to use "zapi.session.verify = False" because the exception occurs when creating the object, not after using the .login() function.

**Comment by szuro** [comment]
I'm afraid it's the direct result of  #150.
This is because it will try to determine the version at `__init__`. If the certificate is invalid, it will produce an error.

This is already addressed in #151.
Until that is merged, the possible workarounds would be:
- set `detect_version=False` when creating the object to skip the unfortunate API call
- provide a custom session object when creating the object

**Comment by amar3lo** [comment]
i got the exact same problem..

**Comment by lukecyca** [comment]
#156 is merged, so I expect this issue is resolved. Please re-open if I am mistaken.

**Comment by matiasba** [comment]
Is this fix in the current release version?

**Comment by isaqueprofeta** [comment]
> Is this fix in the current release version?

In 1.0.0 yeah. just use  zapi = ZabbixAPI(server='https://myzabbix.network', detect_version=False)

**Comment by matiasba** [comment]
Thanks! Does the version detection affects functionality in any way?
