### ISSUE TITLE
Couldn't add New SNMP monitored host

### ISSUE THREAD

**Issue by Warheadjc** [lukecyca/pyzabbix#159]
Hello good sir, maybe you could help me with this, been killing me for the past week.

I want to add host with only the SNMP interface but I keep getting the exception that:

_('Error -32602: Invalid params., Cannot find host interface on "snmp" for item key "agent.hostname".', -32602)_

Here's my code on the host create:
```py
hostcreate = zapi.host.create(
        host= hostname,
        status= 1,
        interfaces=[{
            "type": type,
            "main": 1,
            "useip": 1,
            "ip": ip,
            "dns": "",
            "port": 161,
            "details": {
                    "version": 2,
                    "community": "public"
                       }
        }],
        groups=[{
            "groupid": groupid
        }],
        templates=[{
            "templateid": templateid
        }]
        )
```
Please help!

**Comment by szuro** [comment]
Hi there!
Not sure if still relevant, but my guess would be that you are trying to link a template with items using the Agent interface.

**Comment by anatchai36** [comment]
I have same issue. I don't know how to fix this issue. 
Can anyone help?

**Comment by anatchai36** [comment]
I have try to add snmp interface without templates. it's work.
I'm not sure why cannot add snmp interface with template.

**Comment by l2rTul2N** [comment]
I ever found this issue because that templates have item key agent.hostname.
I think that template can use only on agent interface not snmp interface.
I have try change template without key agent.hostname.It's work.

You can check the key agent.hostname by selecting templates what you want 
and go to tab "items" and view on column "key".

**Comment by szuro** [comment]
Passive agent checks require an Agent interface.
Passive SNMP checks require a SNMP Interface.

This is by design in Zabbix and has nothing to do with this package.
