### ISSUE TITLE
Hostgroup mass add not working

### ISSUE THREAD

**Issue by giovanny07** [lukecyca/pyzabbix#160]
Hi

I try to use host.massadd and got this error. The user have all permissions in zabbix

Best regards

![image](https://user-images.githubusercontent.com/69469456/147620921-355a05bb-c492-46fb-b3ca-7f5c09af3b7c.png)

**Comment by szuro** [comment]
Are you able to get the group via `hostgroup.get`?
Also, do you have permissions to the specified host?

**Comment by giovanny07** [comment]
Yes, hostgroup.get works.
The user has super administrator permission.

**Comment by szuro** [comment]
Could you post the relevant code fragment?
A dump of the request that is sent to Zabbix would be helpful as well.

This is a Zabbix error, so it would be nice to know if the request isn't malformed.

**Comment by giovanny07** [comment]
Error -32500: Application error., You do not have permission to perform this operation.', -32500

`def update_hostgrp_id():
    #Check if host exist
    host_id   = zapi.host.get(filter={"host": [host_name]},output = ["hostid"])
    if (host_id == []):
        print("No existe el host ingresado")
    else:
        print("Si existe el host ingresado: ",host_name)
        # Create host
        hostgrp_update = zapi.host.massadd  ( hosts=[{"hostid":host_id}],
                                            groups=[{
                                                "groupid":hostgrp}]
                                            )
        print(hostgrp_update)`

**Comment by szuro** [comment]
I assume this is what your code looks like:
```python
def update_hostgrp_id(): 
	#Check if host exist
	host_id = zapi.host.get(filter={"host": [host_name]},output = ["hostid"])
	if (host_id == []):
		print("No existe el host ingresado")
	else:
		print("Si existe el host ingresado: ",host_name)
		# Create host
		hostgrp_update = zapi.host.massadd ( hosts=[{"hostid":host_id}], groups=[{ "groupid":hostgrp}] )
		print(hostgrp_update)
```
So:
- `host.massadd` is not meant to create hosts, just to edit existing ones.
- `host_id` is an list, which will cause problems here: `{"hostid":host_id}`
- where does `hostgrp` and `host_name` come from? Are those global variables?

Something like this might work, thou you'll get an `IndexError` if the host doesn't exist
```python
def update_hostgrp_id(): 
	#Check if host exist
	host_id = zapi.host.get(filter={"host": [host_name]},output = ["hostid"])[0]['hostid']
```

**Comment by szuro** [comment]
@lukecyca this Issue is stale and not really a pyzabbix issue.
I think we could close this.
