### ISSUE TITLE
Latest `pyzabbix` code is not in PyPI

### ISSUE THREAD

**Issue by markkuleinio** [lukecyca/pyzabbix#165]
I was troubleshooting a problem in instantiating `ZabbixAPI`, and it took me a long time to realize that the source here in GitHub does _not_ correspond to the `pyzabbix` package in PyPI.

Maybe 1.0.1 should be released?

Thanks for the consideration.

**Comment by markkuleinio** [comment]
Hi @lukecyca, please consider releasing the latest code changes to PyPI. It would help users with various instantiation problems when using custom headers or TLS verification.

**Comment by jooola** [comment]
Should be fixed by #171

**Comment by jooola** [comment]
1.1.0 has been released.
