### ISSUE TITLE
SSL verification disable as described does not work  in version 1.0

### ISSUE THREAD

**Issue by KarlikB** [lukecyca/pyzabbix#167]
Pyzabix mechanism 
zapi.session.verify = False
as described in readme currently not working in version 1.0.

According to the README the sequence is:
```
# Create ZabbixAPI Object
zapi = ZabbixAPI("http://zabbixserver.example.com")
# Disable SSL certificate verification
zapi.session.verify = False
```

But ZabbixAPI constructor now internally calls Zabbix API to get version information before zapi.session.verify variable is set that subsequently ends with SSL verification exception.
See line 95 in __init__.py - "self.api_version()"

If the session is configured and passed to the constructor, everything works
```
sess = requests.Session()
sess.verify = False
zapi = ZabbixAPI("https://some-zabbix.com", sess)
```

Please fix this, maybe simple change in README (use extenally provided session object) is enough.

Thanks and regards,

**Comment by jooola** [comment]
For reference, one can also configure the verify parameter using the REQUESTS_CA_BUNDLE environment variable.

https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification

**Comment by krisavi** [comment]
> Basically duplicate of #165

The issue descriptions or conversations would not give me any clue about issues being duplicate. Yours is about not having latest version in PyPI, while this one is about issue in code.

**Comment by markkuleinio** [comment]
No worries, it was just the fact that there was a fix to the problem presented in this issue but the fixed code was not published for wider use.
