### ISSUE TITLE
Setup automated publish pipeline using CI

### ISSUE THREAD

**Issue by jooola** [lukecyca/pyzabbix#171]
I propose to automate the publishing of a new version to pip using the CI.

I'll only need @lukecyca to setup a secret token that allow one to publish this package to pip.

This can be triggered when pushing a new tag.

**Comment by jooola** [comment]
@lukecyca Could you setup a `PYPI_TOKEN` in the repository secrets so we can publish new releases to pypi using the CI ?

https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github

**Comment by lukecyca** [comment]
Done. It is called `PYPI_API_TOKEN`.
