### ISSUE TITLE
Invalid params., Invalid parameter "/1": unexpected parameter "showsla".

### ISSUE THREAD

**Issue by FlanniganColum** [lukecyca/pyzabbix#202]
When trying to do a service.create i get the above error the payload being sent looks fine from what i can see but i am getting the above error. Is this an issue with the pyzabbix version and zabbix 6.X

Sending: {'jsonrpc': '2.0', 'method': 'service.create', 'params': {'name': 'AIX servers', 'algorithm': 1, 'showsla': 1, 'goodsla': '99.99', 'sortorder': 1}, 'id': 6, 'auth': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}

Response Body: {'jsonrpc': '2.0', 'error': {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter "/1": unexpected parameter "showsla".'}, 'id': 6}

Traceback (most recent call last):
  File "./main.2.0.py", line 154, in mk_father_itservices
    zapi.service.create(name="{}".format(group), algorithm=1, showsla=1, goodsla="{}".format(float(sla_value)), sortorder=1)
  File "/opt/apps/zabbix/availability/venv/lib64/python3.6/site-packages/pyzabbix/api.py", line 265, in __call__
    return self._parent.do_request(self._method, args or kwargs)["result"]
  File "/opt/apps/zabbix/availability/venv/lib64/python3.6/site-packages/pyzabbix/api.py", line 239, in do_request
    error=error,
pyzabbix.api.ZabbixAPIException: ('Error -32602: Invalid params., Invalid parameter "/1": unexpected parameter "showsla".', -32602)

pyzabbix: 1.2.1
Zabbix: 6.0.8

**Comment by markkrj** [comment]
Zabbix have separated SLA and Service endpoints:
https://www.zabbix.com/documentation/6.0/en/manual/api/changes_5.4_-_6.0#service-1

So, not a pyzabbix bug.
