### ISSUE TITLE
httptest create with 68 character name get "value is too long"

### ISSUE THREAD

**Issue by rugenl** [lukecyca/pyzabbix#203]
I'm trying to create an httptest and the name is 68 characters long.  Error message:

`pyzabbix.api.ZabbixAPIException: ('Error -32602: Invalid params., Invalid parameter "/1/name": value is too long.', -32602)`

Zabbix 6.0 web lets me create the test with the long name.

**Comment by jooola** [comment]
Please provide a code sample for us to provide you any help.

**Comment by markkuleinio** [comment]
In my Zabbix 6.0.11 and Zabbix 6.2.4 servers in the GUI the Name fields in web scenarios and steps are limited to 64 characters, so the reported API behaviour with longer name seems consistent with that.

**Comment by rugenl** [comment]
Agree, thanks
