### ISSUE TITLE
How to use proxy

### ISSUE THREAD

**Issue by wongkunkun** [lukecyca/pyzabbix#205]
When I use: zapi = ZabbixAPI("http://zabbixserver.example.com")
How could I use http_proxy and https_proxy?

**Comment by jooola** [comment]
Hi,
I am not sure to understand your question, could you provide more details ?

**Comment by markkrj** [comment]
@jooola I think he has a proxy between his client (python) and Zanbix API. @wongkunkun did you try using HTTP_PROXY env var? Or, if that's not an option and you want to set it in code, create a custom Session object, like:

```python
from requests import Session
from pyzabbix import ZabbixAPI

session = Session()
session.proxies = {
   'http': 'http://192.168.0.1:3128',
   'https': 'http://192.168.0.1:3128',
}

zapi = ZabbixAPI("http://zabbixserver.example.com", session=session)
```
