### ISSUE TITLE
param from trigger.get are ignored

### ISSUE THREAD

**Issue by Christ444** [lukecyca/pyzabbix#216]
Yesterday I just found a bug in API (pyzabbix 1.3)
I would like to get list of trigger with tag but wether I use filter on triggerid or wouldlike to selectTags, it is just ignored. I can only retrieve full list of trigger.
I think it is a bug because I give same param on the curl and it work

`{"triggerids": "1139833", "output": "extend", "selectTags": "extend"}`

or only

`{"output": "extend", "selectTags": "extend"}`

give same result, param just ignored and give full list (without tag, which I really need)

but with curl it work:

```
URL=https://ourZabbix
curl -s --insecure -i -X POST -H 'Content-type:application/json' -d '{"jsonrpc":"2.0","method":"user.login","params":{ "user":"'$user'","password":"'$password'"},"auth":null,"id":0}' $URL/api_jsonrpc.php > TOKEN
AUTHTOKEN=$(awk -F: '/jsonrpc/{gsub(/"/,"",$3);gsub(/,.*/,"",$3);print $3}' TOKEN )

curl --insecure -i -X POST -H 'Content-type:application/json' -d '{"jsonrpc":"2.0","method":"trigger.get","params":{  "triggerids": ["1139833"], "output": "extend", "selectTags": "extend"   },"auth":"'$AUTHTOKEN'","id":0}' $URL/api_jsonrpc.php
```

**Comment by Christ444** [comment]
It seems by giving each params instead of dict of param it work:
`ZabbixAPIObject.trigger.get(triggerids=trigger["triggerid"], output="extend", selectTags="extend") `
instead of 
```
var={"triggerids": [trigger["triggerid"]], "output": "extend", "selectTags": "extend"}
ZabbixAPIObject.trigger.get(var) 
```
using the second way is usually easier since we can update the dict easilly

**Comment by jooola** [comment]
Don't forget to unpack your dict when passing it to the function call:

```patch
 var={"triggerids": [trigger["triggerid"]], "output": "extend", "selectTags": "extend"}
-ZabbixAPIObject.trigger.get(var)
+ZabbixAPIObject.trigger.get(**var) 
```

**Comment by Christ444** [comment]
indeed it work, so the question is why I did not have to do for other calls ?
 I mean I work in that way for all my other call since a while.

**Comment by jooola** [comment]
Could you provide a working example of what you are describing?

**Comment by Christ444** [comment]
Item dict built on multiple levels and after that called in api (without the **, because was not aware of that)
I did it for host, user, usergroup, dashboard, ... also create update delete, ...
It is little bit difficult to extract all these examples from huge code since the dict is built on different level in order to push it on multiples zabbix instance or use import (get) / export (create or update) .
Here for user:
```
...
     userDict = {
           username : u[username],
           'name' : u['name'],
           'surname' : u['surname'],
           'url' : u['url'],
           'autologin' : u['autologin'],
           'autologout' : u['autologout'],
           'lang' : u['lang'],
           'refresh' : u['refresh'],
           userType : u[userType],
           'theme' : u['theme'],
           'rows_per_page' : u['rows_per_page'],
           'usrgrps' : usrgrps, # item built
           'user_medias' : medias # item built
     }
     try:
      ZabbixAPIObjectImp.user.create(userDict)
   ...
```

**Comment by jooola** [comment]
Here is the bit of magic to understand why this is working like this:
https://github.com/lukecyca/pyzabbix/blob/a49401b17287a4fff06d422bf4b8a239ad543be2/pyzabbix/api.py#L274-L278

If you pass a single dict argument, it will be used as a list with a single item `"params": [userDict]` in https://github.com/lukecyca/pyzabbix/blob/a49401b17287a4fff06d422bf4b8a239ad543be2/pyzabbix/api.py#L197

Since the zabbix api allows creating a list of users in a single call, you are not getting any error: https://www.zabbix.com/documentation/current/en/manual/api/reference/user/create

So if the endpoint does not support a list of params, you should have an error.
