### ISSUE TITLE
Getting Hosts/Host Groups

### ISSUE THREAD

**Issue by HansMoleman** [lukecyca/pyzabbix#54]
I am attempting to retrieve my host groups and the hosts that are in them;however, host.get does not return a 'groupid' or 'groupids' parameter. Here's my code:

    for host in zapi.host.get():
        print host['groupids']

and I receive a key error for output:
    KeyError: 'groupids'

Retrieving host by groupids should work as per [Zabbix Documentation](https://www.zabbix.com/documentation/2.4/manual/api/reference/host/get).

How do I retrieve host groups and their associated hosts?

**Comment by lukecyca** [comment]
I suspect you need to try different parameters for `host.get()`. The documentation you linked shows several examples of different parameters and the responses they generate.

**Comment by HansMoleman** [comment]
Thanks for the help. I have tried entering several groupid parameters;however, all my hosts are printed (regardless of the host group/groupid).  Also, when simply printing 'host' in the for loop included above, there are no groupid parameters included. Any other suggestions?

**Comment by lukecyca** [comment]
I'm not sure the exact query you need. You will have to experiment and perhaps ask on the Zabbix forum. This appears to be a question about the Zabbix API in general, not this Python library per se.

**Comment by HansMoleman** [comment]
Sounds good. Thanks for the help!

**Comment by neothematrix** [comment]
HansMoleman, you're misinterpreting the documentation, you can use "groupids" as filter for the host.get call:
zapi.host.get(groupids=[4, 8]) this will extract all hosts that are part of the host groups with ids "8" or "4"

alternatively, you could use: zapi.host.get(selectGroups='extend')  this will extract EVERY hosts together with additional information about the groups in which every host is inserted.

one last option is to call: zapi.hostgroup.get(selectHosts='extend'), this will extract every hostgroup and for every group you'll have additional information about all the hosts included in it.

I hope this help, even if it's not exactly a pyzabbix issue :-)

**Comment by HansMoleman** [comment]
Thanks for the help, guys. I think I got it fixed up with neothematrix's comment. It turns out that the function I was using was converting type of 'groupid' to unicode rather than an int (doh!). Thanks again!

**Comment by lukecyca** [comment]
Thanks @neothematrix!
