### ISSUE TITLE
Alert script helper

### ISSUE THREAD

**Issue by gregswift** [lukecyca/pyzabbix#58]
Would you be open to a subclass being proposed with the intent of providing some wrapper functions for devs writing alert scripts?  I realize the below don't match perfectly, but would be kewl if there was some commonality.

Things like:
https://github.com/PagerDuty/pdagent-integrations/blob/master/bin/pd-zabbix#L44-L54
https://github.com/gregswift/zabbix-alertscript-maintenance/blob/master/scripts/zabbix-maintenance-mode#L18-L19
https://github.com/gregswift/zabbix-alertscript-maintenance/blob/master/scripts/zabbix-maintenance-mode#L21-L28

**Comment by lukecyca** [comment]
Yeah, if you can come up with something that is generally useful then that would be a great addition!

**Comment by neothematrix** [comment]
hi, how should we proceed with this? @gregswift do you intend to write this wrapper and request a pull?

**Comment by gregswift** [comment]
let me talk with our main engineer on the zabbix coding bits.  I do think that we'll get something written.

**Comment by neothematrix** [comment]
@gregswift, I'm cleaning up here, feel free to reopen the issue whenever you have more info!

**Comment by gregswift** [comment]
ya, sorry for the delay and bring iit back into my view.
