### ISSUE TITLE
Add doc or example for configuration.import

### ISSUE THREAD

**Issue by greenmoon55** [lukecyca/pyzabbix#62]
`confimport` method is not documented. I'd like to add example code.

**Comment by neothematrix** [comment]
hi, there is some kind of example of confimport on this closed issue: https://github.com/lukecyca/pyzabbix/issues/41
the documentation of the method is the official Zabbix API documentation, but I agree a nice example code showing how to read and import an XML file would be useful, feel free to branch the project, create the example code inside the example folder and perform a pull request if you intend to write the code, thanks a lot!

**Comment by neothematrix** [comment]
uhm sorry, I've just seen that you did exactly this :) I'll accept the pull request
