### ISSUE TITLE
 Getting Hosts from multiple groups

### ISSUE THREAD

**Issue by PetzJohannes** [lukecyca/pyzabbix#68]
I want to search for all hosts that are located in two specific groups.

When I search with
```
zapi.host.get(output="extend", groupids=[group1, group2])
```
I get all hosts that are linked to one group. This is a logical "or". I am searching for the logical "and".

Is there a solution?

Regards

**Comment by neothematrix** [comment]
hi,
this is more of a question to ask on the Zabbix forum, it's related to how the apis work, not to the actual pyzabbix implementation.
As a workaround, you could split the call into many single call with a single hostgroup filter, then work your data on the python code to find matching hostids.
