### ISSUE TITLE
Could you obfuscate the password during an incorrect sign in

### ISSUE THREAD

**Issue by q1x** [lukecyca/pyzabbix#69]
I get the following response which clearly shows the used password:

pyzabbix.ZabbixAPIException: ("Error -32602: Invalid params., Login name or password is incorrect. while sending {'params': {'password': 'guest', 'user': 'guest'}, 'jsonrpc': '2.0', 'method': 'user.login', 'id': 0}", -32602)

**Comment by neothematrix** [comment]
hey Raymond,
how are you? I just pushed some changes that should fix your issue, there was no need to print the full request json together with the error, you can enable the debug for that.
Thanks for your input and let me know if it works as you expect!
