### ISSUE TITLE
Zabbix 3.0 compatability

### ISSUE THREAD

**Issue by banzayats** [lukecyca/pyzabbix#73]
Is this module compatible with latest version of Zabbix?

**Comment by neothematrix** [comment]
yes.
is it just an informative question or you have proof that something is not working correctly?

**Comment by banzayats** [comment]
It's an informative question.
Currently I'm using pyzabbix with Zabbix 2.4 and planning to migrate to Zabbix 3.0
I've found this [list of changes](https://www.zabbix.com/documentation/3.0/manual/api/changes_2.4_-_3.0) and wondering whether all will work as it should.

**Comment by neothematrix** [comment]
sure, pyzabbix should be fully compatible (it dynamically calls the API, no method is rewritten and needs to be adapted), however your app implementation may need some adjustments if you were using deprecated methods listed on the changes you correctly linked.
