### ISSUE TITLE
Create multiple hostgroups with one request

### ISSUE THREAD

**Issue by ITler** [lukecyca/pyzabbix#74]
Hy,

please, imagine that easy example

    hostgroups_to_create = ['foo', 'bar']
    existing_hgs = api.hostgroup.get(filter={'name': hostgroups_to_create}) # works
    if existing_hgs == []: # if hostgroups not defined, yet
        api.hostgroup.create(
            name=hostgroups_to_create
        ) # Error -32500: Application error.,

I tried a bunch of approaches to pass hostgroups variable content to `name`. (i.e. even such things: `"'%s'" % "','".join(map(str, hostgroups_to_create))`) But I just don't get it. It seems, only passing a string works, but I've only been able to create one hostgroup that way. 
But this is not what I want, as I would like to have one request and one response. I'm new to python, so maybe I even missed a basic syntax?  
However, the code examples didn't help. Could you please help me out?

Thanks
ITler

btw: I'm using zabbix 3

**Comment by neothematrix** [comment]
there are a few issues:
1) you must repeat the "name" property for each hostgroup you want to add
2) you have to use python keyword argument expansion (*argument) when passing the object to the api call

```
hgroups = [ { 'name': 'foo' }, { 'name': 'bar' } ]
api.hostgroup.create(*hgroups)
```
or oneliner:
```
api.hostgroup.create(*[ { 'name': 'foo' }, { 'name': 'bar' } ])
```
this should make it.

**Comment by ITler** [comment]
That's it. Thank you.
