### ISSUE TITLE
Non Standard port on httpd

### ISSUE THREAD

**Issue by esawyja** [lukecyca/pyzabbix#78]
Hi
I'm running Zabbix on a non standard port IE 9000 and I'm having problems with this
[root@centos7 zabbix_install]# ./test.py
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    zapi.login("Admin", "zabbix")
  File "/usr/lib/python2.7/site-packages/pyzabbix/__init__.py", line 68, in login
    self.auth = self.user.login(user=user, password=password)
  File "/usr/lib/python2.7/site-packages/pyzabbix/__init__.py", line 156, in fn
    args or kwargs
  File "/usr/lib/python2.7/site-packages/pyzabbix/__init__.py", line 107, in do_request
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

[root@centos7 zabbix_install]# cat test.py 
#!/usr/bin/python -u

from pyzabbix import ZabbixAPI

zapi = ZabbixAPI("http://172.28.200.166:9000")
zapi.login("Admin", "zabbix")
print "Connected to Zabbix API Version %s" % zapi.api_version()

for h in zapi.host.get(output="extend"):
    print h['hostid']
[root@centos7 zabbix_install]#

Am I doing something wrong or does pyzabbix not cater for non standard ports?

**Comment by neothematrix** [comment]
404 not found, it's not a matter of non-standard port, you used the wrong URL for "ZabbixAPI" initialization, most probably you missed the zabbix directory:
```
zapi = ZabbixAPI("http://172.28.200.166:9000/zabbix/")
```

**Comment by esawyja** [comment]
Hi thanks, realized that as soon as I posted the issue
