### ISSUE TITLE
Can't create web scenarios

### ISSUE THREAD

**Issue by aflavin** [lukecyca/pyzabbix#79]
I'm trying to use pyzabbix to push a list of web scenarios to Zabbix via the api. However, because creating a web scenario requires a nested JSON input to create both the web scenario and the web scenario steps simultaneously I cannot find a way to make it work with pyzabbix. 
For example:
`z.httptest.create(name='Google', hostid='10138', authentication='0', retries='1',
                          steps= ['url=google.com, name=google, no=1'])`
results in the following JSON query being sent to the server:

Sending: {
    "params": {
        "retries": "1",
        "authentication": "0",
        "name": "Google",
        "hostid": "10138",
        "steps": [
            "url=google.com, name=google, no=1"
        ]
    },
    "auth": "****",
    "jsonrpc": "2.0",
    "id": 2,
    "method": "httptest.create"
}

Trying to format a multiline query in correct JSON format and inserting it into the parameter doesn't work because it is parsed and converted by the Python interpreter as far as I can tell:

steps = """ {
                     "name": "google",
                     "url": "google.com",
                     "no": 1
                }"""
`z.httptest.create(name='Google', hostid='10138', authentication='0', retries='1',
                          steps= [steps])'

Sending: {
    "jsonrpc": "2.0",
    "method": "httptest.create",
    "params": {
        "hostid": "10138",
        "name": "Google",
        "steps": [
            " {\n                     \"name\": \"google\",\n                     \"url\": \"google.com\",\n                     \"no\": 1\n                }"
        ],
        "authentication": "0",
        "retries": "1"
    },
    "auth": "*******",
    "id": 2
}
Response Code: 200
Response Body: {
    "jsonrpc": "2.0",
    "id": 2,
    "error": {
        "code": -32602,
        "data": "Web scenario step name cannot be empty.",
        "message": "Invalid params."
    }
}

I'm very new to python and programming in general, and any help would be appreciated. Thank you.

**Comment by neothematrix** [comment]
try this:

**Comment by aflavin** [comment]
Trying
`z.httptest.create(name='Google', hostid='10138', authentication='0', retries='1',
                          steps={'url=google.com, name=google, no=1'})`
results in a type error:
`TypeError: {'url=google.com, name=google, no=1'} is not JSON serializable`

as does 
`z.httptest.create(name='Google', hostid='10138', authentication='0', retries='1',
                          steps=[{'url=google.com, name=google, no=1'}])`

here is the full traceback:
Traceback (most recent call last):
  File "C:/Users/Local user/PycharmProjects/ZabbixWebMonitor/ZabbixWebMonitor.py", line 97, in <module>
    steps=[{'url=google.com, name=google, no=1'}])
  File "C:\Users\Local user\pyzabbix2\lib\site-packages\pyzabbix\__init__.py", line 157, in fn
    args or kwargs
  File "C:\Users\Local user\pyzabbix2\lib\site-packages\pyzabbix\__init__.py", line 99, in do_request
    separators=(',', ': ')))
  File "C:\Program Files\Python35\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python35\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Program Files\Python35\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python35\lib\json\encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "C:\Program Files\Python35\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Program Files\Python35\lib\json\encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {'url=google.com, name=google, no=1'} is not JSON serializable

**Comment by neothematrix** [comment]
right, I didn't think enough, this should work:

```
z.httptest.create(name='Google', hostid='10138', authentication='0', retries='1', steps=[{'url': 'google.com', 'name': 'google', 'no': 1}])

**Comment by aflavin** [comment]
That worked. Thank you very much!

**Comment by amandahla** [comment]
Just to share how I did (after a lot of tries):

```
           query = {
                'name': nome,
                'hostid': hostID,
                'delay': "3m"
            }

            i = 1
            passos = []
            passo = {}
            for c in contexto.split("+"):
                passo['name'] = 'CONTEXTO ' + c 
                passo['url'] = url + c
                passo['no'] = i
                passo['status_codes'] = "200,302"
                passo['timeout'] = 30
                passo['required'] = '<title>.*</title>'

                passos.append(passo)
                i = i+1

            query['steps'] = passos
            out = self.__zapi.httptest.create(**query)
```
