### ISSUE TITLE
drop Python 3.2 support since "requests" library doesn't support it anymore

### ISSUE THREAD

**Issue by neothematrix** [lukecyca/pyzabbix#85]
we should also remove import of the "future" package

**Comment by lukecyca** [comment]
I've removed Py3.2 for the TravisCI tests.

**Comment by hugovk** [comment]
Can this be closed now?

**Comment by neothematrix** [comment]
no, I need a commit to remove the import of the "future" module that backport the unicode compatibility since it's not needed anymore

**Comment by neothematrix** [comment]
now we can close it
