### ISSUE TITLE
It can not use the method "hostgroup.delete" in version 3.0 of zabbix

### ISSUE THREAD

**Issue by tianhunzhixin** [lukecyca/pyzabbix#86]
I use like "zabbix_client.hostgroup.delete(["89"])" to delete group which id is 89, but it raise the esception like "
pyzabbix.ZabbixAPIException: (u'Error -32500: Application error., No permissions to referred object or it does not exist!', -32500)
"
Why??

**Comment by tianhunzhixin** [comment]
in other delete method, it is same problem.
Like host.delete

**Comment by neothematrix** [comment]
hello,
for how dynamic arguments work, you either need to pass just the id as a single value, i.e.:
```
zabbix_client.hostgroup.delete("89")
```

or if you want to pass an array with one or more ids, you need to use the "*" before the object:

```
zabbix_client.hostgroup.delete(*["89"])
```

**Comment by tianhunzhixin** [comment]
OK, Thanks
