### ISSUE TITLE
ZBX-3783, API call mis-constructed

### ISSUE THREAD

**Issue by rburkhal** [lukecyca/pyzabbix#87]
Misconstruction of host.get command to submit an Array not a Object results in erroneous results 

[Command]
{"params": **[**
{
"filter": {"host": ["019615"]}, "output": ["extended"]
}
**]**
, "jsonrpc": "2.0", "method": "host.get", "auth": "b9d8c3c7f0c08bdd2c20f1ddb023cb27", "id": 9}

[Response]
'{"jsonrpc":"2.0","result":[{"hostid":"10096"}],"id":9}'

**Comment by neothematrix** [comment]
hello @rburkhal 
I'm not sure I understand the issue here? Could you elaborate?

**Comment by rburkhal** [comment]
I figured out the issue.
