### ISSUE TITLE
requests.exceptions.HTTPError: 504 error using  trigger.get method

### ISSUE THREAD

**Issue by BigBrotherNA** [lukecyca/pyzabbix#90]
I was trying to use trigger.get method to get all trigger info, but returned 504 Gateway Timeout exception. It never happened before, when I tried to get all the single host trigger info by specifying the host name using filter keyword it worked well. I thought it resulted from the increasing amount of hosts which means large number of trigger it returned. I have about 1800 hosts so far. Any solutions to this problem? Thank you!

**Comment by neothematrix** [comment]
Maybe you exhausted the php allowed memory on your web server, check the
apache (or whatever webserver you are using) error log, you may see the
reason of the 504 error and act accordingly.

**Comment by MattParr** [comment]
You can patch to enable paging.
It works well.
https://support.zabbix.com/plugins/servlet/mobile#issue/ZBXNEXT-2132
