### ISSUE TITLE
expandData is deprecated since zabbix 2.4

### ISSUE THREAD

**Issue by 0312birdzhang** [lukecyca/pyzabbix#92]
So current_issues.py has issues

```
triggers = zapi.trigger.get(only_true=1,
                            skipDependent=1,
                            monitored=1,
                            active=1,
                            output='extend',
                            expandDescription=1,
                            expandData='host',
                            )
```

**Comment by lukecyca** [comment]
Thanks for reporting this. I will not be able to fix this anytime soon, but I would very much appreciate a Pull Request. :)

**Comment by samilko** [comment]
You can use this request to get data from zabbix > 3.0:

       triggers = zapi.trigger.get(
              filter={'value':1},
              only_true=1,
              sortfield="hostname",
              skipDependent=1,
              monitored=1,
              active=1,
              maintenance=0,
              output=[
              "triggerid",
              "description",
              "priority",
              "lastchange",
              "value"
              ],
              expandDescription=1,
              withLastEventUnacknowledged=1,
              selectHosts=["name"]
              )

**Comment by 0312birdzhang** [comment]
@samilko  Thank you very much.
I use this code resolved
```
triggers = zapi.trigger.get(
                                only_true=1,
                                skipDependent=1,
                                monitored=1,
                                active=1,
                                output='extend',
                                expandDescription=1,
                                withLastEventUnacknowledged=1,
                                )
```

**Comment by neothematrix** [comment]
thanks for reporting it, I fixed the example on the latest commit https://github.com/lukecyca/pyzabbix/commit/56c5a206b350968f633a1f927d318c823a619ff8
