### ISSUE TITLE
How to perform 'user.logout'?

### ISSUE THREAD

**Issue by DenisBY** [lukecyca/pyzabbix#95]
How to perform 'user.logout' after api call is done? Otherwise I have millions of records in 'session' table.
See https://support.zabbix.com/browse/ZBX-12659 and https://www.zabbix.com/documentation/3.4/manual/api/reference/user/login

**Comment by Ph0enixxx** [comment]
Can the MYSQL Timing Trigger work ?

**Comment by neothematrix** [comment]
@DenisBY: you can just use "user.logout" call at the end of your scripts, or are you having issue with this?

**Comment by neothematrix** [comment]
but actually, we should include user.logout in our examples, for the sake of correctness

**Comment by DenisBY** [comment]
We have our own library for several zabbix tasks which uses pyzabbix, and we do login in `init` function in this library. Our library is used in permanently running service.
Currently I don't see any possibility to call `user.logout` after each API call, but I'm not so good in Python.

**Comment by neothematrix** [comment]
I'm not sure of how your application is set, I'm not super expert in python either maybe you can call user.logout at the end of the main function of your library?
We cannot add an "automatic" logout to our library because that would mean calling a logout every time an api call is made, and I think most of the users here actually call the login once, then perform a lot of api calls, and then they might call the user.logout, but if you have other suggestion, let us know!

**Comment by DenisBY** [comment]
We managed it using context and `with`. I.e.:
```python
class ZabbixSession:
    def __init__(self, options):
        self.options = options
        self.zapi = ZabbixAPI(self.options['url'])

    def __enter__(self):
        self.zapi.login(self.options['user'], self.options['password'])

    def __exit__(self, type, value, traceback):
        self.zapi.do_request('user.logout')

class ZabMon():
    def __init__(self, options):
        self.options = options

    def get_instance_id(self, instance_name):
        with ZabbixSession(self.options) as zapi:
            hostids = zapi.do_request(
                "host.get",
                {
                    "output": "hostids",
                    'search': {
                        'name': instance_name
                    }
                }
            )
            instance = [host['hostid'] for host in hostids['result']]
            return instance
```

**Comment by neothematrix** [comment]
thanks for the feedback!
