### ISSUE TITLE
Error occurred when using pickle or django.core.cache to cache zapi

### ISSUE THREAD

**Issue by xianfuxing** [lukecyca/pyzabbix#97]
```
api= ZabbixAPI('http://myzabbix/')
pickle.dumps(api)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'ZabbixAPIObjectClass' object is not callable
```
Finally, I followed https://stackoverflow.com/questions/2049849/why-cant-i-pickle-this-object
by adding:
```
    def __setstate__(self, d):
        self.__dict__.update(d)

    def __getstate__(self):
        return self.__dict__
```
in ZabbixAPI class, and works fine.

I doubt if there is a way to dumps zapi without inspecting ZabbixAPI class?
Could you adivise?

**Comment by neothematrix** [comment]
Hi!
I'm not very familiar with pickle or caching, I guess the logging facility (see the example in the Readme) is not useful in this case?

**Comment by xianfuxing** [comment]
@neothematrix , I want to cache the zapi instance as we are not necessary to initialize the ZabbixAPI instance in each request (I am using in Django project). The logging module doesn't provide serialization function and is not useful in this case. Finally, the solution is combined with django.core.cache & customize the ZabbixAPI class.

**Comment by neothematrix** [comment]
hello @xianfuxing I'm sorry I cannot be helpful here, but if you think the ZabbixAPI change you proposed will not break anything and could provide additional functionality, could you please submit a pull request with your change?
thanks!
