### ISSUE TITLE
ImportError: cannot import name ZabbixMetric

### ISSUE THREAD

**Issue by niraj8241** [lukecyca/pyzabbix#98]
Hi,

I have a Debian GNU/Linux 8 \n \l OS on Amazon EC2. I am trying to run a zabbix API using the pyzabbix module.

My import looks like below.
from pyzabbix import ZabbixAPI, ZabbixMetric, ZabbixSender

This works perfectly fine on Ubuntu 14.04 but on Debian i am getting this error while running my sript.

```
Traceback (most recent call last):
  File "salttozabbix.py", line 7, in <module>
    from pyzabbix import ZabbixAPI, ZabbixMetric, ZabbixSender
ImportError: cannot import name ZabbixMetric
```
What am i doing wrong here.

**Comment by neothematrix** [comment]
I think you got the "wrong" pyzabbix module, this project doesn't contain any "ZabbixMetric" or "ZabbixSender" class, it seems you are referring to another py-zabbix module: https://github.com/adubkov/py-zabbix

**Comment by neothematrix** [comment]
feel free to reopen if you think there is an issue
